# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',  url: '/about'}
- {name: 'Donate', url: '/donate'}
- {name: 'Equipment',       url: '/equipment'}
- {name: 'Gallery',      url: '/gallery'}
- {name: 'Memes',              url: '/memes'}
- {name: 'Reports',  url: '/reports'}
- {name: 'Press', url: '/press'}
- {name: 'Contributors', url: '/contributors'}
- {name: 'Partners',  url: '/partners'}
- {name: 'Contact',  url: '/contact'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/sucho_org'}
- {icon: 'facebook', link:   'https://www.facebook.com/sucho.initiative'}
- {icon: 'bluesky', link: 'https://bsky.app/profile/sucho-org.bsky.social'}
- {icon: 'github', link: 'https://github.com/sucho-archiving/'}
#- {icon: 'rss', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
